tipAmout added to template
coopcycle/coopcycle-web pull request #2616
Opened 2021-07-09 22:25 UTC by AniaCuapio

2021-07-21 17:29 UTC, alexsegura requested changes

2021-07-21 17:29 UTC, alexsegura commented on templates/order/summary.txt.twig
> +{{ 'order.summary.heading'|trans({ '%number%': order.number, '%id%': order.id , '%tipAmount%' order.tipAmount}) }}
Actually, it should be `order.getAdjustmentsTotal('tip')`, instead of `order.tipAmount`

2021-07-21 17:29 UTC, alexsegura commented on templates/order/summary.txt.twig
> +{{ 'order.summary.heading'|trans({ '%number%': order.number, '%id%': order.id , '%tipAmount%' order.tipAmount}) }}
You also need to modify the translation [order.summary.heading](https://github.com/coopcycle/coopcycle-web/blob/40d422d861c1d1c91a204003d1dec9652941c441/translations/messages.en.yml#L292) to show the tip amount

2021-08-04 22:56 UTC, AniaCuapio commented
![Captura de pantalla de 2021-08-04 17-51-45](https://user-images.githubusercontent.com/60676655/128265822-88593a72-a46c-42de-931b-d92c393c90d2.png)

2021-08-04 22:59 UTC, AniaCuapio commented
Maybe we can improve the way it is showed, but at least now it is showed.

2021-08-05 08:15 UTC, alexsegura approved these changes

2021-08-05 08:16 UTC, merged