Multiple time slots for stores
coopcycle/coopcycle-web pull request #3138
Opened 2022-02-17 22:18 UTC by alexsegura

Fixes #3135 

It's now possible to attach multiple time slots to a store. It's still necessary to set a default time slot for retro-compatibility. 

<img width="1226" alt="Capture d’écran 2022-02-17 à 23 15 54" src="https://user-images.githubusercontent.com/1162230/154580194-4c2431f1-6b0f-436b-be27-28be9bae7869.png">

---

When multiple slots are configured, it's possible to switch in the delivery form.

![multi_slot](https://user-images.githubusercontent.com/1162230/154580346-f2b289a4-c853-4719-a1cd-c7661d06221c.gif)

2022-02-18 16:00 UTC, lucasferraro requested changes

2022-02-20 18:58 UTC, alexsegura commented on src/Form/StoreType.php
> +                    'required' => false,
No, it shouldn't be required, because you can still have a store with no time slot(s), like before.

2022-02-21 15:01 UTC, lucasferraro commented on src/Form/StoreType.php
> +                    'required' => false,
Oh ok :+1:

2022-02-21 15:14 UTC, lucasferraro approved these changes

2022-02-24 13:40 UTC, merged